version: "3.7"

services:

  mysql:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: mysql
    restart: always
    ports:
      - "port:port"

    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "pharmacy"
      MYSQL_USER: "userdb"
      MYSQL_PASSWORD: "userdbpwd"

    volumes:
      - ./db:/var/lib/mysql:rw
    networks:
      mysql_network:
        aliases:
          - mysql_host

volumes:
  schemas: {}
networks:
  mysql_network: